# Generated by Django 6.0.5 on 2026-05-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fix_outstandingtoken_user_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'ordering': ['market_cap_rank']},
        ),
        migrations.AddField(
            model_name='coin',
            name='market_cap_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
