# Generated by Django 6.0.5 on 2026-05-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
