# Generated by Django 6.0.5 on 2026-05-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_refresh_token_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh_token_created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh_token_expiry',
        ),
    ]
