# Generated by Django 6.0.5 on 2026-06-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='price_change_24h',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
