# Generated by Django 6.0.5 on 2026-07-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='coin',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
