# Generated by Django 6.0.5 on 2026-08-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_user_image_coin_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coin',
            index=models.Index(fields=['coin_name'], name='coins_coin_na_7c1fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='coin',
            index=models.Index(fields=['market_cap_rank'], name='coins_market__60de0b_idx'),
        ),
    ]
